apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsfix
  namespace: default
spec:
  selector:
    matchLabels:
      kubernetes.io/os: linux
  template:
    metadata:
       labels:
          kubernetes.io/os: linux
    spec:
      containers:
      - image: mcr.microsoft.com/oss/nginx/nginx:1.13.12-alpine
        imagePullPolicy: Never
        name: dnsfix
        resources: {}
        volumeMounts:
        - mountPath: /host
          name: host-root
        command: ["/bin/sh", "-c"]
        args:
          - chroot /host /bin/bash -c "dhclient -r; dhclient; sleep infinity"
      hostIPC: true
      hostNetwork: true
      hostPID: true
      preemptionPolicy: PreemptLowerPriority
      priority: 0      
      volumes:
      - hostPath:
          path: /
          type: ""
        name: host-root
